### ISSUE TITLE
Robot keytabs not supported

### ISSUE THREAD

**Issue by areeda** [duncanmmacleod/ciecplib#127]
The function `find_principal` in kerberos.py does not allow slashes ('/') in the principal name. Current robot principals look like: `dqr/robot/dqr.ligo.caltech.edu@LIGO.ORG`

```
dqr-ping -q
Traceback (most recent call last):
  File "/home/dqr/.conda/envs/dqr-igwn39/bin/dqr-ping", line 8, in <module>
    sys.exit(main())
  File "/home/dqr/.conda/envs/dqr-igwn39/lib/python3.9/site-packages/dqrxfer/dqr_ping.py", line 75, in main
    cjar = utils.get_shib_cookie_jar(url)
  File "/home/dqr/.conda/envs/dqr-igwn39/lib/python3.9/site-packages/dqrxfer/utils.py", line 42, in get_shib_cookie_jar
    cookie = ciecplib.get_cookie(url, kerberos=kerberos)
  File "/home/dqr/.conda/envs/dqr-igwn39/lib/python3.9/site-packages/ciecplib/requests.py", line 55, in _wrapper
    sess = Session(
  File "/home/dqr/.conda/envs/dqr-igwn39/lib/python3.9/site-packages/ciecplib/sessions.py", line 59, in __init__
    idp = krb5_realm(find_krb5_principal())
  File "/home/dqr/.conda/envs/dqr-igwn39/lib/python3.9/site-packages/ciecplib/kerberos.py", line 127, in realm
    user, realm = principal.rsplit("@", 1)
ValueError: invalid kerberos principal 'dqr'
```

**Comment by duncanmmacleod** [comment]
This was resolved by #128.
